### ISSUE TITLE
Generate test data?

### ISSUE THREAD

**Issue by tomjaguarpaw** [qfpl/sv#11]
Is there any chance you would consider *generating* your test data rather than committing 70MB of files to the repository?

**Comment by gwils** [comment]
Yes. Thank you for bringing this up. I'm making this my top priority.

Those files are for benchmarking. I didn't want to randomly generate benchmark data each run, because it would introduce unnecessary variability that would make benchmark results more difficult to compare over time.
Rather than being committed to the repository, this could all be generated by starting from a fixed seed  using manual seed-passing. I didn't do this in the first place because it was difficult to do with hedgehog (my preferred means of random generation). This was a mistake on my part.

Here are some options I see:

1. Do nothing. Leave the big files in the repo. This will make it frustrating to clone and fork.
2. Change the means of benchmarking and delete the offending files. They will still live on in the git history, but this can be sidestepped by using a shallow clone. Forks and full clones will still be affected.
3. Change the means of benchmarking and remove the offending files from the entire git history using [git filter-branch or similar](https://help.github.com/articles/removing-sensitive-data-from-a-repository/). This will butcher the history until this point a little and make git archaeology cryptic in future.
4. Change the means of benchmarking and squash the entire history into a single commit. There will be no cryptic history because there won't be any.

1 and 2 are unsatisfying to me because they don't really fix the problem.
3 and 4 will break everyone's forks (like yours!) and cause some pain. sv has only just released though, so there aren't many forks to break. If we're going to butcher the git history, now is the time to do so.

I think 3 is the best option. It causes less history damage than 4, and completely fixes the problem unlike 1 and 2. What are your thoughts? Do you see another option that I've missed?

I'm going to work on fixing the benchmarking now, and unless there's a compelling argument made that 3 is the wrong option, I will go ahead with it ASAP.

**Comment by tomjaguarpaw** [comment]
I don't have any objection to 3.  There are only 3 forks tracked in GitHub and I doubt there are many more outside of it.  Anyone's work that builds on the tip of master can always be rebased to the new master.

**Comment by gwils** [comment]
I have rewritten the history using `git filter-branch` as described. If you have a clone or fork, make sure to `git pull --rebase`

Apologies for any inconvenience caused.

**Comment by gwils** [comment]
@bitemyapp @tmcgilchrist this will affect your forks ^

**Comment by bitemyapp** [comment]
@gwils right-o. Thanks for the heads up.

**Comment by tmcgilchrist** [comment]
Noted, thanks @gwils
