### ISSUE TITLE
Named encoding

### ISSUE THREAD

**Issue by vrom911** [qfpl/sv#20]
I wonder if it's possible to implement something like `NameDecode'` but for encoding, like `NameEncode`? It would be very handy.

**Comment by gwils** [comment]
released in sv-1.1.1

**Comment by vrom911** [comment]
🎉 Thank you, @gwils! I will give it a try.

**Comment by gwils** [comment]
Please let me know how it goes. I'm open to tweaking the design.

It's also worth pointing out that I haven't benchmarked encoding at all yet, so I have no idea whether it performs well.

**Comment by vrom911** [comment]
Thank you again for that! I like how it's working now. 
The only concern I have is whether it's possible to implement a function that could work without lenses but with just fields?

**Comment by gwils** [comment]
Do you mean something like "encodeOf" which takes a field accessor instead of an optic? 

`encodeOf` has the type 

```
encodeOf :: Getting (First a) s a -> Encode a -> Encode s
```

Since field accessors are just functions `(s -> a)`, the function corresponding to `encodeOf` would have the type

```
(s -> a) -> Encode a -> Encode s
```

which is the type of `contramap`. So you can use `contramap fieldName` and then `<>` them together the same way one would do with `encodeOf`. I should add this to the encoding example and maybe split that example up.
